
import { Word, User, Comment } from './types';

export const MOCK_WORDS: Word[] = [
  {
    id: '1',
    term: 'Gabbar',
    pronunciation: '/ɡab·bar/',
    dialect: 'Cypriot Dialect',
    turkishEquivalent: 'Kapari / Gebre Otu',
    definition: 'Güneşli bölgelerde yetişen, tomurcukları turşu yapılan çalımsı bir bitki.',
    exampleSentence: 'Annem her bahar dağa çıkar, gabbar toplardı.',
    exampleTranslation: 'My mother used to go up the mountain every spring to pick capers.',
    imageUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBdghWO9Y7W4FpoQ42Eab-A_Px9bqci9GmpVsWriOqo-2BzXEi3x98Lr8ifgGmDo1CzbaL1HeFtIhEfv-iYuWIXQsFZC0_TdRvfXV2_HmIppjFfB2lMtHXXd5CDJb6OSHXFTTbBLOS8znJUgyusbzIcxJsY8RmKRAcCs-Uv63mrHY7eTSDkshB4rDT_srklM3VHOi7UKhUFzxPPNB6Z1XZ7oFZfR0P03Ke9uBhJCVbfOTQhyHG8SgIwWjsroWA-gh_0zIwGqnrFL2yn',
    likes: 1200,
    commentsCount: 12,
    author: 'ayse_kibrisli',
    createdAt: '2 saat önce'
  },
  {
    id: '2',
    term: 'Hellim',
    pronunciation: '/hel·lim/',
    dialect: 'Cypriot Heritage',
    turkishEquivalent: 'Kıbrıs Peyniri',
    definition: 'Kıbrıs kökenli, yarı sert, tuzlu ve genellikle ızgara yapılarak yenen peynir türü.',
    exampleSentence: 'Sabah kahvaltısında taze hellim ızgara yaptık.',
    exampleTranslation: 'We grilled fresh halloumi for breakfast.',
    imageUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuA3B4u9J9CWQUIWIE8KEhDOQe56krXvq9MMPvrCL0ZwBO-dz1Iyx9nHfTmTJWyYdwOEjlmHbju1581IUvZnhH_m_Srh6mqS8e-t-vMLgC1Xh7N4SPILWEH5OhBJ4pmVJOfE5W4gLimExdtC_mjLUOz4ReYPlfOZ3_xssa1V1AGlHcLKjpDUHU5KcfTt9aDvOhmMfz_Vh8OTBAw-RaJ85TNe71V0aymBRuacXdQkRjrW71vhXoXxJevfowDd6EeTnHaQjN4RQNHrqxt9',
    likes: 3400,
    commentsCount: 89,
    author: 'gurme_kibris',
    createdAt: '5 saat önce'
  },
  {
    id: '3',
    term: 'Gancelli',
    pronunciation: '/gan·cel·li/',
    dialect: 'Cypriot Dialect',
    turkishEquivalent: 'Demir Kapı',
    definition: 'Genellikle bahçe veya tarla girişlerinde bulunan demir parmaklıklı kapı.',
    exampleSentence: 'Gancelli paslanmış, bir yağlamak lazım.',
    exampleTranslation: 'The garden gate is rusted, it needs some oiling.',
    imageUrl: 'https://picsum.photos/seed/gate/800/400',
    likes: 850,
    commentsCount: 24,
    author: 'lefkosali_genç',
    createdAt: '1 gün önce'
  },
  {
    id: '4',
    term: 'Zivana',
    pronunciation: '/zi·va·na/',
    dialect: 'Cypriot Tradition',
    turkishEquivalent: 'Üzüm Rakısı',
    definition: 'Üzüm posasından yapılan geleneksel Kıbrıs içkisi, güçlü alkollü.',
    exampleSentence: 'Dedeler sofrada zivana içerken eskiden kalan hikayeleri anlatırlardı.',
    exampleTranslation: 'The elders would tell old stories while drinking zivania at the table.',
    imageUrl: 'https://picsum.photos/seed/zivania/800/400',
    likes: 2100,
    commentsCount: 45,
    author: 'kibris_gelenekleri',
    createdAt: '3 saat önce'
  },
  {
    id: '5',
    term: 'Molehiya',
    pronunciation: '/mo·le·hi·ya/',
    dialect: 'Cypriot Cuisine',
    turkishEquivalent: 'Yahudi Baklası / Mülühiye',
    definition: 'Yapraklarından sebze yemeği yapılan, Kıbrıs mutfağında özel yeri olan bitki.',
    exampleSentence: 'Annem molehiya yapmış, kokusu evin her tarafına yayıldı.',
    exampleTranslation: 'My mother cooked molehiya, its aroma spread throughout the house.',
    imageUrl: 'https://picsum.photos/seed/molehiya/800/400',
    likes: 1650,
    commentsCount: 38,
    author: 'kibris_mutfagi',
    createdAt: '6 saat önce'
  },
  {
    id: '6',
    term: 'Şeftali',
    pronunciation: '/şef·ta·li/',
    dialect: 'Cypriot Delicacy',
    turkishEquivalent: 'Kıbrıs Köftesi',
    definition: 'Kıyma ve baharatların domuz ağı zarına sarılarak ızgarada pişirilen geleneksel Kıbrıs yemeği.',
    exampleSentence: 'Pazar günü mangalda şeftali yaptık, mis gibi kokuyor.',
    exampleTranslation: 'We grilled sheftalia on Sunday, it smells amazing.',
    imageUrl: 'https://picsum.photos/seed/sheftalia/800/400',
    likes: 2800,
    commentsCount: 67,
    author: 'mangal_ustasi',
    createdAt: '8 saat önce'
  },
  {
    id: '7',
    term: 'Pırpıra',
    pronunciation: '/pır·pı·ra/',
    dialect: 'Cypriot Dialect',
    turkishEquivalent: 'Dağınık / Perişan',
    definition: 'Saçları darmadağın, giysileri düzensiz olan kişi için kullanılan söz.',
    exampleSentence: 'Sabah sabah pırpıra gibi okula gitme, saçını düzelt.',
    exampleTranslation: 'Don\'t go to school looking so disheveled in the morning, fix your hair.',
    imageUrl: 'https://picsum.photos/seed/pirpira/800/400',
    likes: 920,
    commentsCount: 18,
    author: 'kibris_sozcuk',
    createdAt: '12 saat önce'
  },
  {
    id: '8',
    term: 'Kelle',
    pronunciation: '/kel·le/',
    dialect: 'Cypriot Slang',
    turkishEquivalent: 'Arkadaş / Ahbap',
    definition: 'Samimi arkadaş, dost anlamında kullanılan günlük konuşma ifadesi.',
    exampleSentence: 'Kellem, bu akşam sahile gidelim mi?',
    exampleTranslation: 'Buddy, shall we go to the beach tonight?',
    imageUrl: 'https://picsum.photos/seed/kelle/800/400',
    likes: 1450,
    commentsCount: 31,
    author: 'lefkosa_genclik',
    createdAt: '1 gün önce'
  },
  {
    id: '9',
    term: 'Biddata',
    pronunciation: '/bid·da·ta/',
    dialect: 'Cypriot Dialect',
    turkishEquivalent: 'Patates',
    definition: 'Kıbrıs ağzında patatese verilen isim, genellikle kızartması meşhurdur.',
    exampleSentence: 'Akşama biddata kızartması yapalım.',
    exampleTranslation: 'Let\'s fry some potatoes for dinner.',
    imageUrl: 'https://picsum.photos/seed/biddata/800/400',
    likes: 560,
    commentsCount: 15,
    author: 'patates_sever',
    createdAt: '2 saat önce'
  },
  {
    id: '10',
    term: 'Gabira',
    pronunciation: '/ga·bi·ra/',
    dialect: 'Cypriot Toast',
    turkishEquivalent: 'Kızarmış Ekmek',
    definition: 'Mangalda veya ateşte kızartılmış ekmek dilimi.',
    exampleSentence: 'Hellimin yanına gabira da yap.',
    exampleTranslation: 'Make some toasted bread with the halloumi.',
    imageUrl: 'https://picsum.photos/seed/gabira/800/400',
    likes: 890,
    commentsCount: 22,
    author: 'mangalci_baba',
    createdAt: '4 saat önce'
  },
  {
    id: '11',
    term: 'Hırpo',
    pronunciation: '/hır·po/',
    dialect: 'Cypriot Slang',
    turkishEquivalent: 'Saf / Salak',
    definition: 'Biraz saf, dünyadan bihaber veya sakar kişiler için kullanılan hafif argo söz.',
    exampleSentence: 'Tam bir hırposun, anahtarı yine içeride unuttun.',
    exampleTranslation: 'You are such a goof, you forgot the keys inside again.',
    imageUrl: 'https://picsum.photos/seed/hirpo/800/400',
    likes: 1100,
    commentsCount: 45,
    author: 'argo_sozluk',
    createdAt: '6 saat önce'
  },
  {
    id: '12',
    term: 'Basdelli',
    pronunciation: '/bas·del·li/',
    dialect: 'Cypriot Sweet',
    turkishEquivalent: 'Susamlı Tatlı',
    definition: 'Harnup pekmezi ve susam ile yapılan geleneksel Kıbrıs tatlısı.',
    exampleSentence: 'Kahvenin yanında basdelli harika gider.',
    exampleTranslation: 'Pastelli goes great with coffee.',
    imageUrl: 'https://picsum.photos/seed/basdelli/800/400',
    likes: 2300,
    commentsCount: 60,
    author: 'tatli_krizim',
    createdAt: '10 saat önce'
  },
  {
    id: '13',
    term: 'Golyandro',
    pronunciation: '/gol·yan·dro/',
    dialect: 'Cypriot Herb',
    turkishEquivalent: 'Kişniş',
    definition: 'Ayrelli ve diğer yemeklerde sıkça kullanılan aromatik ot.',
    exampleSentence: 'Salataya taze golyandro doğradım.',
    exampleTranslation: 'I chopped fresh coriander into the salad.',
    imageUrl: 'https://picsum.photos/seed/golyandro/800/400',
    likes: 750,
    commentsCount: 12,
    author: 'baharatci',
    createdAt: '1 gün önce'
  },
  {
    id: '14',
    term: 'Nor',
    pronunciation: '/nor/',
    dialect: 'Cypriot Dairy',
    turkishEquivalent: 'Lor Peyniri',
    definition: 'Hellim yapımından artan peynir altı suyundan elde edilen taze peynir.',
    exampleSentence: 'Sabah nor böreği yedik.',
    exampleTranslation: 'We ate nor pastry (nor böreği) for breakfast.',
    imageUrl: 'https://picsum.photos/seed/nor/800/400',
    likes: 1500,
    commentsCount: 30,
    author: 'sut_urunleri',
    createdAt: '1 gün önce'
  },
  {
    id: '15',
    term: 'Zibil',
    pronunciation: '/zi·bil/',
    dialect: 'Cypriot Expression',
    turkishEquivalent: 'Çöp / Çok Fazla',
    definition: 'Gereksiz kalabalık veya çöp anlamında kullanılır. Ayrıca "çok fazla" anlamında pekiştirme yapar.',
    exampleSentence: 'Sokakta zibil gibi kedi var.',
    exampleTranslation: 'There are tons of cats on the street.',
    imageUrl: 'https://picsum.photos/seed/zibil/800/400',
    likes: 670,
    commentsCount: 8,
    author: 'sokak_agzi',
    createdAt: '2 gün önce'
  },
  {
    id: '16',
    term: 'Banabulya',
    pronunciation: '/ba·na·bul·ya/',
    dialect: 'Cypriot Place',
    turkishEquivalent: 'Belediye Pazarı',
    definition: 'Lefkoşa\'daki tarihi belediye pazarı (Bandabuliya).',
    exampleSentence: 'Banabulya\'dan taze meyve aldım.',
    exampleTranslation: 'I bought fresh fruit from Bandabuliya.',
    imageUrl: 'https://picsum.photos/seed/banabulya/800/400',
    likes: 3100,
    commentsCount: 95,
    author: 'lefkosa_gezgini',
    createdAt: '2 gün önce'
  }
];

export const MOCK_USER: User = {
  id: 'user1',
  name: 'Ayşe Yılmaz',
  username: 'ayseyilmaz_kktc',
  bio: 'Kıbrıs ağzı ve kültürü meraklısı. Yasemin kokulu kelimeler peşinde. 🌸',
  location: 'Gazimağusa, KKTC',
  avatar: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDbS1Rh8ZGR-8LknOXjyt-v5LhoKj__cNBQ5NPnLhWBMvNMNfX32Jin2GUDPBg1mMLCtWO9GD3FkFnKlwc_RjSFwKBx5XAiIImqa2HTDD3vfptS3DFmmT8wSgrKyOm_GdrI-YAnE_u82xdr3eFDCRtyP73-KGnOHytvaOCfZE-1vKdROYxhWupFzzwth8uOqAjiSEzsh2ZtBF6cfo1oHDUCIcmIfCwq4TR8vRJ3YiWed3Lb4I1Kuqjf-QHEH21oIvXDvRtKNxrl6vZG',
  stats: {
    wordsCount: 124,
    votesCount: '3.5k',
    followersCount: 892
  }
};

export const MOCK_COMMENTS: Comment[] = [
  {
    id: 'c1',
    authorName: 'Ayşe Kıbrıslı',
    authorAvatar: 'https://lh3.googleusercontent.com/aida-public/AB6AXuA-WveoRZ0dYGoLl0Yp66XUZkramv9ZXwhtXItgH_BzbpfhfjYs-kOxJ4iUSK0EOfuQprtIzlRiEbm22fCzeO93oXMAGpopl3POzb8HpFsZ02U9eK-8v90aOFasMZ8ew5YVhsHdxrNdORYansefXztzhj26qg32qG6yHHKCd5SIXVCxK1Zx-xdO412TdUTjbJYT70QuLp5iF9G3gXnC0HtXTAU3HY1pe_zQvWpWMCU1_fw3jwjHz9CxF_nMD2Ier10MS4_tOw7tnBH2',
    content: 'My grandmother makes the best pickled gabbar! The trick is to soak them in water for a week to remove the bitterness before pickling. 🌿',
    likes: 24,
    timeAgo: '2h ago'
  },
  {
    id: 'c2',
    authorName: 'Mehmet Can',
    authorAvatar: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCuiF3NqSWIrxXKUBaYhgyHFolRD0rWwMljTVzefrWOerLt1sFgo2E67c3py-Kk7rsUDNQOsafBwRyBglSSqbs22X5phnpSrKZT4CHRS6neCLcim0FDNE4WpJImFHefdGQKExqFoK-vMIHWgPLiQOnuLkuHSlajAKlR78Nq3TzJ_Z6J-ROKGTPwRU06OGeC06rjSv1ENGMSYGzC9dHzuovWvMOsWj1cjQuCe2Qur_uL3-KAzLqNi_wlTkbPNChL3uKIuTC8HIhX9yNM',
    content: "Is this also used in salads or just as a pickle? I've seen it growing near Kyrenia castle.",
    likes: 8,
    timeAgo: '5h ago'
  }
];
